---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipwright-build-controller
  namespace: shipwright-build
spec:
  replicas: 1
  selector:
    matchLabels:
      name: shipwright-build
  template:
    metadata:
      labels:
        name: shipwright-build
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: shipwright-build-controller
      containers:
        - name: shipwright-build
          image: ko://github.com/shipwright-io/build/cmd/shipwright-build-controller
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BUILD_CONTROLLER_LEADER_ELECTION_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CONTROLLER_NAME
              value: "shipwright-build"
            - name: GIT_CONTAINER_IMAGE
              value: ko://github.com/shipwright-io/build/cmd/git
            - name: GIT_ENABLE_REWRITE_RULE
              value: "false"
            - name: IMAGE_PROCESSING_CONTAINER_IMAGE
              value: ko://github.com/shipwright-io/build/cmd/image-processing
            - name: BUNDLE_CONTAINER_IMAGE
              value: ko://github.com/shipwright-io/build/cmd/bundle
            - name: WAITER_CONTAINER_IMAGE
              value: ko://github.com/shipwright-io/build/cmd/waiter
          ports:
            - containerPort: 8383
              name: metrics-port
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics-port
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics-port
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
